#items: TYPE,QUANTITY,int %CHANCE(total ~= 100),DURABILITY(optional)
#potions: TYPE,DURATION(seconds),AMPLIFIER
#xp: level to give and amount of lapis gived (-1 -> random between 1 and 3)
#potions: TYPE,level,boolean extend,boolean splash
DIAMOND_ORE:
  items:
    - DIAMOND_HELMET,1,20
    - DIAMOND_CHESTPLATE,1,20
    - DIAMOND_LEGGINGS,1,20
    - DIAMOND_BOOTS,1,20
    - DIAMOND_PICKAXE,1,10
    - DIAMOND_SWORD,1,10
LAPIS_ORE:
  effects:
    - ABSORPTION,10,1
    - BLINDNESS,5,1
    - DAMAGE_RESISTANCE,10,1
    - FAST_DIGGING,10,1
    - FIRE_RESISTANCE,10,1
    - HEAL,3,1
    - HEALTH_BOOST,15,1
    - POISON,5,1
    - POISON,5,2
    - REGENERATION,5,1
IRON_ORE:
  items:
    - STICK,1,19
    - IRON_INGOT,1,19
    - DIAMOND,1,19
    - ARROW,3,19
    - ARROW,2,19
    - COMPASS,1,5
EMERALD_ORE:
  xp: -1
GOLD_ORE:
  items:
    - WOOD,16,12
    - IRON_SWORD,1,12
    - DIAMOND_SWORD,1,12
    - TNT,1,12
    - FLINT_AND_STEEL,1,12,4
    - GOLDEN_APPLE,1,12
    - LAVA_BUCKET,1,12
    - WATER_BUCKET,1,12
    - BOW,1,12
  potions:
    - INSTANT_HEAL,1,false,true
    - INSTANT_DAMAGE,1,false,true
  entity:
    - CREEPER, 20
